In [1]:
import tensorflow as tf

2024-05-31 05:05:58.774317: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-31 05:05:58.778091: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-31 05:05:58.820540: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-31 05:05:59.825679: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [3]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)
tensor_one_d = tf.constant([1,2,3,4,5])
print(tensor_one_d)
tensor_two_d = tf.constant([[1,2,3],[4,5,6]])
print(tensor_two_d)
tensor_three_d = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor_three_d)

print(tensor_three_d.shape)
print(tensor_three_d.ndim)


tensor_four_d = tf.constant([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],[[[13,14,15],[16,17,18]],[[19,20,21],[22,23,24]]]])
print(tensor_four_d)
print(tensor_four_d.shape)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
(2, 2, 3)
3
tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]]]], shape=(2, 2, 2, 3), dtype=int32)
(2, 2, 2, 3)


2024-05-29 15:24:13.861196: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:282] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


In [4]:
tensor_zero_D_string = tf.constant("Hello World")
print(tensor_zero_D_string)

tf.Tensor(b'Hello World', shape=(), dtype=string)


In [5]:
tensor_one_D_string = tf.constant(["Hello","World"])
print(tensor_one_D_string)

tf.Tensor([b'Hello' b'World'], shape=(2,), dtype=string)


In [6]:
tensor_two_D_string = tf.constant([["Hello","World"],["Welcome To", "Tensorflow"]])
print(tensor_two_D_string)

tf.Tensor(
[[b'Hello' b'World']
 [b'Welcome To' b'Tensorflow']], shape=(2, 2), dtype=string)


# Convert Numpy Array to Tensor

In [7]:
import numpy as np
np_array = np.array([1,2,3,4,5])
print(np_array)

[1 2 3 4 5]


In [8]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int64)


<h1>tf.eye</h1>
<h4 style="color: skyblue;">Construct an identity matrix, or a batch of matrices.</h4>

In [9]:
tensorflow_eye = tf.eye(
    3,
    num_columns=None,
    batch_shape=[2],
    dtype=tf.dtypes.float32,
    name=None
)
print(tensorflow_eye)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(2, 3, 3), dtype=float32)


In [10]:
tensorflow_eye = tf.eye(
    3,
    num_columns=None,
    batch_shape=[2, 2],
    dtype=tf.dtypes.float32,
    name=None
)
print(3*tensorflow_eye)

tf.Tensor(
[[[[3. 0. 0.]
   [0. 3. 0.]
   [0. 0. 3.]]

  [[3. 0. 0.]
   [0. 3. 0.]
   [0. 0. 3.]]]


 [[[3. 0. 0.]
   [0. 3. 0.]
   [0. 0. 3.]]

  [[3. 0. 0.]
   [0. 3. 0.]
   [0. 0. 3.]]]], shape=(2, 2, 3, 3), dtype=float32)


# tf.fill
<h4 style="color: skyblue;">Creates a tensor filled with a scalar value.<br>
tf.fill evaluates at graph runtime and supports dynamic shapes based on other runtime tf.Tensors, unlike tf.constant(value, shape=dims), which embeds the value as a Const node.</h4>

In [11]:
fill_tensor = tf.fill(
    [2, 3], 5, name=None, layout=None
)
print(fill_tensor)

tf.Tensor(
[[5 5 5]
 [5 5 5]], shape=(2, 3), dtype=int32)


# tf.random.normal
<h4 style="color: skyblue;">Outputs random values from a normal distribution.</h4>

In [12]:
random_tensor = tf.random.normal(
    [2, 3], mean=100.0, stddev=1.0, dtype=tf.dtypes.float32, seed=None, name=None
)
print(random_tensor)

tf.Tensor(
[[100.55963  99.92206 102.2915 ]
 [ 99.77823  97.92244  99.25039]], shape=(2, 3), dtype=float32)


# tf.random.uniform
<h4 style="color: skyblue;">The generated values follow a uniform distribution in the range [minval, maxval). The lower bound minval is included in the range, while the upper bound maxval is excluded.

For floats, the default range is [0, 1). For ints, at least maxval must be specified explicitly.

In the integer case, the random integers are slightly biased unless maxval - minval is an exact power of two. The bias is small for values of maxval - minval significantly smaller than the range of the output (either 2<sup>32</sup> or 2<sup>64</sup>).</h4>

In [3]:
uniform_tensor = tf.random.uniform(
    [2, 3], minval=0, maxval=10, dtype=tf.dtypes.float32, seed=None, name=None
)
print(uniform_tensor)

tf.Tensor(
[[9.610163   0.02893567 3.727703  ]
 [3.2467532  5.7105303  5.356349  ]], shape=(2, 3), dtype=float32)


In [14]:
tf.random.set_seed(6)
print(tf.random.uniform(shape=[5], maxval=3, dtype=tf.int32, seed=10))

print(tf.random.uniform(shape=[2, 3], maxval=3, dtype=tf.int32, seed=10))

print(tf.random.uniform(shape=[5], maxval=3, dtype=tf.int32, seed=10))

print(tf.random.uniform(shape=[2,3], maxval=3, dtype=tf.int32, seed=10))

tf.Tensor([1 2 2 1 2], shape=(5,), dtype=int32)
tf.Tensor(
[[2 1 1]
 [2 1 0]], shape=(2, 3), dtype=int32)
tf.Tensor([0 1 1 0 0], shape=(5,), dtype=int32)
tf.Tensor(
[[1 0 2]
 [0 2 0]], shape=(2, 3), dtype=int32)


In [15]:
tf.random.set_seed(6)
print(tf.random.uniform(shape=[5], maxval=3, dtype=tf.int32, seed=10))

print(tf.random.uniform(shape=[2, 3], maxval=3, dtype=tf.int32, seed=10))

print(tf.random.uniform(shape=[5], maxval=3, dtype=tf.int32, seed=10))

print(tf.random.uniform(shape=[2,3], maxval=3, dtype=tf.int32, seed=10))

tf.Tensor([1 2 2 1 2], shape=(5,), dtype=int32)
tf.Tensor(
[[2 1 1]
 [2 1 0]], shape=(2, 3), dtype=int32)
tf.Tensor([0 1 1 0 0], shape=(5,), dtype=int32)
tf.Tensor(
[[1 0 2]
 [0 2 0]], shape=(2, 3), dtype=int32)


# Indexing

In [24]:
tensor_indexed = tf.constant([1,2,3,4,5, 25, 89, 9, 26])
print(tensor_indexed[2:6])
print(tensor_indexed[:-3])

tf.Tensor([ 3  4  5 25], shape=(4,), dtype=int32)
tf.Tensor([ 1  2  3  4  5 25], shape=(6,), dtype=int32)


In [29]:
for i in range(3, 10, 2):
    print(i)

3
5
7
9


In [31]:
for i in tensor_indexed[2:6]:
    print(i)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)


<h4>Indexing for matrix</h4>

In [3]:
tensor_two_d_matrix = tf.constant([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(tensor_two_d_matrix[:3, :2])
print(tensor_two_d_matrix.shape)

tf.Tensor(
[[1 2]
 [4 5]
 [7 8]], shape=(3, 2), dtype=int32)
(4, 3)
