In [4]:
import tensorflow as tf
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)
tensor_one_d = tf.constant([1,2,3,4,5])
print(tensor_one_d)
tensor_two_d = tf.constant([[1,2,3],[4,5,6]])
print(tensor_two_d)
tensor_three_d = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor_three_d)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
