In [2]:
import tensorflow as tf
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)
tensor_one_d = tf.constant([1,2,3,4,5])
print(tensor_one_d)
tensor_two_d = tf.constant([[1,2,3],[4,5,6]])
print(tensor_two_d)
tensor_three_d = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor_three_d)

print(tensor_three_d.shape)
print(tensor_three_d.ndim)


tensor_four_d = tf.constant([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],[[[13,14,15],[16,17,18]],[[19,20,21],[22,23,24]]]])
print(tensor_four_d)
print(tensor_four_d.shape)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
(2, 2, 3)
3
tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]]]], shape=(2, 2, 2, 3), dtype=int32)
(2, 2, 2, 3)


In [12]:
tensor_zero_D_string = tf.constant("Hello World")
print(tensor_zero_D_string)

tf.Tensor(b'Hello World', shape=(), dtype=string)


In [13]:
tensor_one_D_string = tf.constant(["Hello","World"])
print(tensor_one_D_string)

tf.Tensor([b'Hello' b'World'], shape=(2,), dtype=string)


In [11]:
tensor_two_D_string = tf.constant([["Hello","World"],["Welcome To", "Tensorflow"]])
print(tensor_two_D_string)

tf.Tensor(
[[b'Hello' b'World']
 [b'Welcome To' b'Tensorflow']], shape=(2, 2), dtype=string)


# Convert Numpy Array to Tensor

In [15]:
import numpy as np
np_array = np.array([1,2,3,4,5])
print(np_array)

[1 2 3 4 5]


In [17]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int64)


<h1>tf.eye</h1>
<h4 style="color: skyblue;">Construct an identity matrix, or a batch of matrices.</h4>

In [28]:
tensorflow_eye = tf.eye(
    3,
    num_columns=None,
    batch_shape=[2],
    dtype=tf.dtypes.float32,
    name=None
)
print(tensorflow_eye)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(2, 3, 3), dtype=float32)


In [30]:
tensorflow_eye = tf.eye(
    3,
    num_columns=None,
    batch_shape=[2, 2],
    dtype=tf.dtypes.float32,
    name=None
)
print(3*tensorflow_eye)

tf.Tensor(
[[[[3. 0. 0.]
   [0. 3. 0.]
   [0. 0. 3.]]

  [[3. 0. 0.]
   [0. 3. 0.]
   [0. 0. 3.]]]


 [[[3. 0. 0.]
   [0. 3. 0.]
   [0. 0. 3.]]

  [[3. 0. 0.]
   [0. 3. 0.]
   [0. 0. 3.]]]], shape=(2, 2, 3, 3), dtype=float32)


# tf.fill
<h4 style="color: skyblue;">Creates a tensor filled with a scalar value.<br>
tf.fill evaluates at graph runtime and supports dynamic shapes based on other runtime tf.Tensors, unlike tf.constant(value, shape=dims), which embeds the value as a Const node.</h4>

In [35]:
fill_tensor = tf.fill(
    [2, 3], 5, name=None, layout=None
)
print(fill_tensor)

tf.Tensor(
[[5 5 5]
 [5 5 5]], shape=(2, 3), dtype=int32)
